#!/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13

try:
    from mkdocs_document_dates.cache_manager import update_cache
except Exception:
    import sys
    # Normal exit (0 status code), don't affect subsequent git actions
    sys.exit(0)

if __name__ == "__main__":
    update_cache()